### ISSUE TITLE
[Question] Can this be configured to run tests spread out through the project?

### ISSUE THREAD

**Issue by akonwi** [UziTech/atom-jasmine2-test-runner#26]
The default test runner only runs tests in the `spec/` directory. Does this test runner allow running tests scattered in other parts of the project? I essentially want to glob `/lib/**/*-spec.js`

**Comment by UziTech** [comment]
https://github.com/UziTech/atom-jasmine2-test-runner/blob/7e60e7a8ac98f0fc3968b3d868fa48fd62bc93b2/lib/create-runner.js#L73

At the moment Atom passes the `testPaths` as a ['spec' or 'test'](https://github.com/atom/atom/blob/1a4e6c4c8548bf75a3428eade5060194cea189b6/src/workspace-element.js#L320-L324) folder when running the package spec window.

You can specify any folder from the command line by running

```sh
atom --test /path/to/any/folder
```

Atom will pass that folder as the test path to the test runner.

`atom-jasmine2-test-runner` will look in every folder that is passed in `testPaths` for the suffix option (`-spec` by default) and run that file.

Are you looking for a way to override the `testPaths` variable and provide your own path for the package specs window?

**Comment by akonwi** [comment]
Yea ideally, I want to override testPaths for the window

**Comment by UziTech** [comment]
In [v1.3.0](https://github.com/UziTech/atom-jasmine2-test-runner/releases/tag/v1.3.0) I added an option to override the [testPaths](https://github.com/UziTech/atom-jasmine2-test-runner#api) in the window.

You can specify the test paths in your runner options:

```js
// in package.json
{
  "name": "my-package",
  // ...
  "atomTestRunner": "./test-runner.js"
}
```

```js
// in test-runner.js
const { createRunner } = require('atom-jasmine2-test-runner');

const options = {
  testPaths: ["./lib"],
};

module.exports = createRunner(options);
```

the test runner will look in `./lib` for the tests instead of `./spec`

This option only applies to the Atom spec window so in your CI environment you will need to run

```sh
atom --test ./lib
```

**Comment by akonwi** [comment]
Awesome! Thanks a lot!
